### ISSUE TITLE
Too many arguments

### ISSUE THREAD

**Issue by RagingSquirrel** [babolivier/matrix-poll-bot#12]
After git clone and setup of the environment go build fails:

 - - -
 $ go build
 \#   _/home/matrix-bot-poll-bot/matrix-poll-bot
 ./main.go:303:25: too many arguments in call to h.Client.Sync
         have (number)
         want ()
 - - - 

Any ideas?

**Comment by babolivier** [comment]
Hey, sorry about this, I think I tampered with my local copy of gomatrix and forgot about it. It should be fixed now.
