### ISSUE TITLE
Can't use with pantalaimon due to filter

### ISSUE THREAD

**Issue by turt2live** [babolivier/matrix-poll-bot#20]
The filter ends up stripping out the keys of the content, so the encrypted messages can't be decrypted. It's a bit weird that Synapse sends down the events even though they don't match the type, but that's a different issue.

https://github.com/t2bot/matrix-poll-bot/commit/7db40f1a653943a36596f55c45e5996d62c03897 is all that's needed to get the thing working over Pantalaimon.

**Comment by babolivier** [comment]
I've fixed this in https://github.com/babolivier/matrix-poll-bot/commit/a8df55036814bd5bd1fae7e2a877ad397a616b71 by adding a configuration flag to allow skipping filter creation.

**Comment by kamilr** [comment]
Are You able to get it work on current synapse? May I ask for configuration file for Pantalaimon? For me it's just working for rooms without E2EE.
