### ISSUE TITLE
new line in element PC client not possible

### ISSUE THREAD

**Issue by strikegun** [babolivier/matrix-poll-bot#21]
a new line is not possible in the element client for PC.
Enter sends the !poll command straight away.
Better would be a !startpoll and !endpoll for setting up a poll.

**Comment by babolivier** [comment]
Heya, in Element you need to hit Shift+Enter to add a second line to your message!

**Comment by strikegun** [comment]
I tried that. but it don't accept it. shift+Enter is for the Bot no usefull CRLF

**Comment by babolivier** [comment]
How do you mean? I've just tested and succeeded at creating a poll, using shift+enter to create new lines:

![Peek 2021-01-25 22-30](https://user-images.githubusercontent.com/5547783/105768740-1bec4b80-5f5d-11eb-802f-e01f963ffcbb.gif)

(note that unlike the example on the readme I haven't added an empty line between the question and the answers; this is entirely optional, the bot just ignores empty lines)
